### ISSUE TITLE
Bug reading resources from a file (resource parsing) - "maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by t3mp1337** [zeroq/peanalysis#3]
Hi Jan,

I found bug when I tried to analyze some files:

> RuntimeError: maximum recursion depth exceeded

Here you can download one of the file that it didn't succeed to analyze:
https://ufile.io/vul1n

SHA256: 19f4bd7107c3cee673aa406fce035b32adcb921ff7eb04a9819d19faf29bb04e

In the `__init__` function you are reading the sections.
One of the row is:
`self.carvedFileSize = self.readSectionHeader(self.sectionHeader, i, resourceRVA)`

Inside `readSectionHeader(...)` you are calling:
`result = self.recursiveReadTree(i, index, 8, spaces = 2)`

I think there is a problem with `recursiveReadTree(...)`, it looks like it loops forever but eventually stops with error that this is not a PE file.

It seems that you read the .rsrc correctly but there is a problem to read the **resources** inside it.

I don't know to tell you what is the problem yet (I still need to check), I hope you can look on that also.
Maybe you will find the problem faster.

More failed binaries can be found here (it will be available for 30 days):
https://ufile.io/kn64h

**Comment by t3mp1337** [comment]
I also check calc.exe (32 bit) and saw that it doesn't show me all the results.

Here is a comprasion between the results from your code (in the bottom) and from C# library PeNet (the above):
![capture](https://cloud.githubusercontent.com/assets/27521195/25147172/426899de-247f-11e7-9051-ecf2ee009555.PNG)

First problem that I found is at row 419 and 421:
row 419: `if rootDir_NumberOfIdEntries>0:`
row 421: `while counter < rootDir_NumberOfIdEntries:`

You are treating only the `NumberOfIdEntries`. 
You should consider also the `NumberOfNamedEntries`.

As Microsoft mentioned [here](https://msdn.microsoft.com/en-us/library/ms809762.aspx):

> IMAGE_RESOURCE_DIRECTORY_ENTRY DirectoryEntries[]
> This field isn't really part of the IMAGE_RESOURCE_DIRECTORY structure. Rather, it's an array of IMAGE_RESOURCE_DIRECTORY_ENTRY structures that immediately follow the IMAGE_RESOURCE_DIRECTORY structure. **The number of elements in the array is the sum of the NumberOfNamedEntries and NumberOfIdEntries fields**. The directory entry elements that have name identifiers (rather than integer IDs) come first in the array.
> 

I noticed that you separated them:
```
if rootDir_NumberOfNamedEntries>0:
...
if rootDir_NumberOfIdEntries>0:
```

But on the `rootDir_NumberOfNamedEntries` condition I don't see any special thing.

I think it should be something like
new row: number_of_entries = `rootDir_NumberOfIdEntries + rootDir_NumberOfNamedEntries`
row 419: `if number_of_entries > 0:`
row 421: `while counter < number_of_entries:`

But there are still other problems.

References that can help:
https://blackholesunsite.wordpress.com/tag/pe-file/

**Comment by zeroq** [comment]
thanks, I'll check and fix it asap.

**Comment by zeroq** [comment]
Looks like it is working now. Thanks again for your help!
