### ISSUE TITLE
Resource parsing bug - overwriting entries

### ISSUE THREAD

**Issue by t3mp1337** [zeroq/peanalysis#4]
Hi Jan,

I saw your last fixes, looks better now but there is still an issue.

Between rows 415 - 430 you have bug.

On the second while loop you are overwriting the array you initialized on the first loop.

For example, if you will analyze calc.exe (32 bit) it has:
```
rootDir_NumberOfNamedEntries = 3
rootDir_NumberOfIdEntries = 5
```

First while loop:
`while counter < rootDir_NumberOfNamedEntries`

Will ran 3 times from 0 to 2:
```
self.resourceData[0] = result
self.resourceData[1] = result
self.resourceData[2] = result
```

The second while loop:
`while counter < rootDir_NumberOfIdEntries`

Will run 5 times from 0 to 4 because you reset the counter to 0 in the second loop so the result will be:
```
self.resourceData[0] = result
self.resourceData[1] = result
self.resourceData[2] = result
self.resourceData[3] = result
self.resourceData[4] = result
```

Now you can see that index 0 - 2 were overwrite by the second loop.

You can solve it if you will replace rows 415 - 430 with:
```
number_of_entries = rootDir_NumberOfNamedEntries + rootDir_NumberOfIdEntries
for counter in range(0, number_of_entries):
    result = self.recursiveReadTree(i, index, 8, spaces=2)
    if result != None:
        self.resourceData[counter] = result
    counter += 1
    index += 8
```

**Comment by zeroq** [comment]
Hi,
agreed, just the counter += 1 is not needed due to the switch to a for-loop. thanx again
